/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Architecture: typeof import('./components/Index/Architecture.vue')['default']
    CoreValue: typeof import('./components/Index/CoreValue.vue')['default']
    Cube: typeof import('./components/Index/WhyEfficient/cube.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    FocusOn: typeof import('./components/Index/FocusOn.vue')['default']
    FocusOnPhone: typeof import('./components/Index/FocusOnPhone.vue')['default']
    Footer: typeof import('./components/Index/Footer.vue')['default']
    GetReady: typeof import('./components/Index/GetReady.vue')['default']
    GlobalScale: typeof import('./components/Index/GlobalScale.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    Index: typeof import('./components/Index/Code/Index.vue')['default']
    InfoItem: typeof import('./components/Index/Products/InfoItem.vue')['default']
    MakeEasy: typeof import('./components/Index/MakeEasy.vue')['default']
    MakeFor: typeof import('./components/Index/MakeFor/index.vue')['default']
    NewProducts: typeof import('./components/Index/NewProducts.vue')['default']
    OpenVideo: typeof import('./components/Index/OpenVideo.vue')['default']
    PicText: typeof import('./components/PicText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveWhat: typeof import('./components/Index/SaveWhat.vue')['default']
    SloganPage: typeof import('./components/Index/SloganPage.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
    WhyEfficient: typeof import('./components/Index/WhyEfficient/index.vue')['default']
  }
}
